customer_classification_features:
  convert_columns:
    t0_order_date: datetime
    payment_installments: int
  dropna_columns:
    - payment_type
    - payment_value
    - payment_installments
  drop_columns:
    - first_gmv
    - total_items_value
    - customer_city
    - dow
    - month
    - customer_unique_id
    - t0_order_id
    - t0_order_date
    - payment_installments
    - top_category_by_priciest_item